import type { Metadata } from "next";
import "./globals.css";
import TopBar from "./_components/TopBar";
import { Exo } from 'next/font/google'
import NavBar from "./_components/NavBar";
import Footer from "./_components/Footer";
import { Toaster } from "sonner";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_context/CartContextProvider";
import WishListContextProvider from "./_context/WishListContextProvider";

const exo = Exo({
  subsets: ['latin'],
  weight: '500'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Fresh Cart</title>
      </head>
      <body
        className={`${exo.className} antialiased`}>
        <MySessionProvider>
          <CartContextProvider>
            <WishListContextProvider>
              <TopBar />
              <NavBar />
              {children}
              <Toaster />
              <Footer />
            </WishListContextProvider>
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
